from abc import ABC, abstractmethod


class RobotInterface(ABC):
    @abstractmethod
    def move_forward(self, distance: float | None = None) -> None: ...
    @abstractmethod
    def move_backward(self, distance: float | None = None) -> None: ...
    @abstractmethod
    def turn_left(self, angle: float | None = None) -> None: ...
    @abstractmethod
    def turn_right(self, angle: float | None = None) -> None: ...
    @abstractmethod
    def stop(self) -> None: ...
    @abstractmethod
    def cleaner_down(self) -> None: ...
    @abstractmethod
    def cleaner_up(self) -> None: ...
    @abstractmethod
    def start_cleaning(self) -> None: ...
    @abstractmethod
    def stop_cleaning(self) -> None: ...
    @abstractmethod
    def execute_pass(self) -> None:
        """Complete one cleaning traverse and report success or raise on failure."""
        ...
    @abstractmethod
    def get_status(self) -> dict: ...

    def set_speed(self, speed: float) -> None:
        raise NotImplementedError("speed control is not available")
